baseURL = "https://ltosp.uk/"
languageCode = "en-us"
title = "LT-OSP Field Guide"
theme = ["lt-osp", "fuse-search"]

[taxonomies]
  guild = "guilds"

[params]
  themeColor = "theme-base-09"
  description = "An interactive pocket guide to the Lorien Trust Role-Playing (L.T.R.P.) System's Occupational Skill Points"

[[menu.guilds]]
  name = "Miscellaneous"
  identifier = "misc"
  weight = -1